import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  containerPadding: {
    padding: 20,
    paddingTop: 40,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 12,
    color: '#2d3436',
  },
  item: {
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 10,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ececec'
  },
  itemTitulo: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2d3436'
  },
  itemSub: {
    fontSize: 12,
    color: '#636e72',
    marginTop: 4
  },
  checkbox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center'
  },
  checkboxRound: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6C5CE7'
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 30,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    ...Platform.select({
      web: { cursor: 'pointer' },
    }),
  },
  fabIcon: {
    color: '#fff',
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '700',
  },
  stats: {
    fontSize: 16,
    color: '#636e72',
    marginBottom: 16,
    fontWeight: '600',
  },
  checklistContainer: {
    backgroundColor: '#f7f7fc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    marginTop: -2,
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  checklistBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checklistText: {
    fontSize: 15,
    color: '#2d3436',
  },
  checklistVazio: {
    color: '#636e72',
    fontStyle: 'italic',
    fontSize: 14,
    marginTop: 4,
  },
  flex: { flex: 1 },
  modalFlex: { flex: 1 },
  container2: { padding: 20, paddingTop: 40 },
  modalContainer: { padding: 20, paddingTop: 40 },
  header: { fontSize: 26, fontWeight: '700', marginBottom: 18, color: '#2d3436' },
  label: { fontSize: 14, color: '#636e72', marginTop: 12, marginBottom: 6 },
  input: { backgroundColor: '#fff', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, borderWidth: 1, borderColor: '#dfe6e9' },
  textArea: { minHeight: 100, textAlignVertical: 'top' },
  actions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 20 },
  saveButton: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 8, backgroundColor: '#6C5CE7' },
  saveText: { color: '#fff', fontWeight: '700' },
  cancelButton: { paddingVertical: 10, paddingHorizontal: 14, marginRight: 8, borderRadius: 8, backgroundColor: '#dfe6e9' },
  cancelText: { color: '#2d3436', fontWeight: '600' },
  tipoBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, marginRight: 8, borderWidth: 1, borderColor: '#dfe6e9', backgroundColor: '#fff' },
  tipoBtnAtivo: { backgroundColor: '#6C5CE7', borderColor: '#6C5CE7' },
  tipoTexto: { color: '#2d3436', fontWeight: '600' },
  tipoTextoAtivo: { color: '#fff', fontWeight: '700' },
  inputErro: { borderColor: '#ff7675' },
  errorText: { color: '#ff7675', marginTop: 6, marginBottom: -6 },
  deleteButton: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 8, backgroundColor: '#ff6b6b' },
  deleteText: { color: '#fff', fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center' },
  modalConfirmacao: { backgroundColor: '#fff', borderRadius: 12, padding: 20, width: '85%', maxWidth: 320 },
  modalTitulo: { fontSize: 18, fontWeight: '700', color: '#2d3436', marginBottom: 10 },
  modalMensagem: { fontSize: 14, color: '#636e72', marginBottom: 20, lineHeight: 20 },
  modalBotoes: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
});
